apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest 
        resources:
        ports:
        - containerPort: 8000

#sreeharshav/rollingupdate:v5
#jayasurya/rollingupdate:v1
